#YAML

  logPath: ./etc/awesomeProject_log.log
  debugLogLevel: true
  sheetConfig:
      path: /mnt/c/Users/F15/Downloads/Календарь Заселения.xlsx
      name: ноя2024-ноя2025
      startColumNum: 6
      yearAndMonthRowNum: 1
      daysRowNum: 2
      startRow: 4
      apartmentColumNum: 4